---
- hosts: localhost

  vars:
    repo_name: "{{ playbook_dir }}/turris-openwrt"
    vagrant_plugins_file: "{{lookup('file', '~/.vagrant.d/plugins.json') }}"
    vagrant_plugin: vagrant-lxc
    packages:
    - vagrant
    - lxc

  tasks:
    - name: Clone turris os repo from Gitlab
      git:
        repo: https://gitlab.labs.nic.cz/turris/openwrt.git
        dest: "{{ repo_name}}"

    - name: Ensure that vagrant and lxc are installed
      apt:
        name: "{{ packages }}"
      become: yes

    - name: Install lxc vagrant plugin
      command: vagrant plugin install vagrant-lxc
      when:
        - vagrant_plugins_file['installed'] | json_query("[?installed==vagrant_plugin]")
